fixtures:
  symlinks:
    zookeeper: '#{source_dir}'
  forge_modules:
    stdlib: "puppetlabs/stdlib"
    staging: "nanliu/staging"
    java:
      repo: "puppetlabs/java"
      ref: "1.5.0"
    tomcat:
      repo: "puppetlabs/tomcat"
      ref: "1.5.0"
