fixtures:
  symlinks:
    zookeeper: '#{source_dir}'
  forge_modules:
    stdlib: "puppetlabs/stdlib"
    archive: "puppet-archive"
    staging: "nanliu/staging"
    java:
      repo: "puppetlabs/java"
      ref: "1.5.0"
    tomcat:
      repo: "puppetlabs/tomcat"
      ref: "1.5.0"
    wget:
     repo: "maestrodev/wget"
     ref: "1.7.3"
