fixtures:
  symlinks:
    zookeeper: '#{source_dir}'
  forge_modules:
    concat:
      repo: "puppetlabs/concat"
      ref: "1.2.5"
    stdlib: 
      repo: "puppetlabs/stdlib"
      ref: "4.25.0"
    staging: 
      repo: "puppet/staging"
      ref: "1.0.7"
    java:
      repo: "puppetlabs/java"
      ref: "1.6.0"
    tomcat:
      repo: "puppetlabs/tomcat"
      ref: "1.6.0"
