---
driver:
  name: vagrant
  network:
    - ["forwarded_port", {guest: 8080, host: 8080}]
  customize:
    name: 'puppet-zookeeper'

provisioner:
  name: puppet_apply
  manifests_path: examples
  ignore_spec_fixtures: true
  puppet_environment: vagrant
  hiera_data_path: hieradata
  hiera_data_remote_path: /etc/puppet/hieradata
  puppet_debug: true

transport:
  name: sftp

platforms:
  - name: centos-7.5

verifier:
  name: serverspec
  remote_exec: false
  extra_flags: '--require spec_helper -I spec/acceptance'

suites:
  - name: zookeeper
    provisioner:
      manifest: init.pp
      custom_facts:
        packagecloud_master_token: <%= ENV['PACKAGECLOUD_MASTER_TOKEN'] %>
    verifier:
      patterns:
        - 'spec/acceptance/**_spec.rb'
