---
driver:
  name: vagrant

provisioner:
  name: puppet_apply
  manifests_path: test/integration

platforms:
  - name: centos-7.2

suites:
  - name: default
    driver:
      network:
        - ["forwarded_port", {guest: 8080, host: 8080}]
        - ["private_network", {ip: "192.168.33.33"}]
    provisioner:
      manifest: default/init.pp
      custom_facts:
        packagecloud_master_token: <%= ENV['PACKAGECLOUD_MASTER_TOKEN'] %>
