require 'spec_helper'

describe 'zookeeper' do

  context 'When Exhibitor installed' do
    describe 'Tomcat Server Info' do
      subject { command('/usr/bin/java -cp /opt/apache-tomcat/lib/catalina.jar org.apache.catalina.util.ServerInfo') }
      its(:stdout) { should include 'Apache Tomcat/8.5.2' }
    end
    describe 'Tomcat Home Directory' do
       subject { file('/home/tomcat') }
       it { should be_directory }
       it { should be_owned_by 'tomcat' }
    end
  end

  context 'When Exhibitor configured' do
    describe file('/etc/rc.d/init.d/zookeeper') do
      it { should_not exist }
    end

    describe file('/etc/init.d/zookeeper') do
      it { should_not exist }
    end

    describe command('/usr/bin/curl -v http://127.0.0.1:8080/exhibitor/v1/config/get-state') do
      its(:stdout) { should include '"clientPort":2181' }
      its(:stdout) { should include '"connectPort":2888' }
      its(:stdout) { should include '"electionPort":3888' }
    end
  end

  context 'When Exhibitor running' do
    describe command('sleep 60') do
      its(:exit_status) { should eq 0 }
    end

    describe command('/usr/lib/zookeeper/bin/zkCli.sh get /') do
      its(:stdout) { should include 'dataVersion ='}
    end

    describe file('/usr/lib/zookeeper/conf/zoo.cfg') do
      it { should exist }
      it { should be_file }
      its(:content) { should include '#Auto-generated by Exhibitor' }
      its(:content) { should include 'initLimit=10' }
      its(:content) { should include 'syncLimit=5' }
      its(:content) { should include 'tickTime=2000' }
      its(:content) { should include 'autopurge.snapRetainCount=30' }
      its(:content) { should include 'autopurge.purgeInterval=4' }
    end

    describe port(8080) do
      it { should be_listening }
    end

    describe command('/usr/bin/wget -O - http://127.0.0.1:8080/exhibitor/v1/cluster/state') do
      its(:stdout) { should match /"description":"(serving|latent)"/ }
    end

    describe service('tomcat-exhibitor') do
      it { should be_running.under('systemd') }
    end
  end

end
